version: "3.8"
services:
  postgres:
    container_name: postgres-auth
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "backend"
  redis:
    container_name: redis-session
    image: redis
    ports:
      - 6379:6379
